/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetfst;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Hp
 */
public class Commandes extends javax.swing.JFrame {

    /**
     * Creates new form Commandes
     */
    public Commandes() {
        initComponents();
        RemplirComboUtilisateur();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        IDCmd = new javax.swing.JTextField();
        prixCmd = new javax.swing.JTextField();
        libelleCmd = new javax.swing.JTextField();
        qteCmd = new javax.swing.JTextField();
        dateCmdTxtH = new javax.swing.JLabel();
        dateCmd = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tab_Commande = new javax.swing.JTable();
        ajtBtn = new javax.swing.JButton();
        cherBtn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        CmbUtilisateur = new javax.swing.JComboBox();
        Refresh = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("Commandes"); // NOI18N

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("French Script MT", 1, 50)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageProjet/icons8-create-50.png"))); // NOI18N
        jLabel1.setText("Commandes");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, 350, 70));

        jPanel3.setBackground(java.awt.Color.white);
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.setOpaque(false);
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ID Commande");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 46, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Libellé");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 90, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Quantité");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 137, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Prix");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 184, -1, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Date");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 227, -1, -1));

        IDCmd.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jPanel3.add(IDCmd, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 40, 425, 29));

        prixCmd.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jPanel3.add(prixCmd, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 178, 425, 30));

        libelleCmd.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jPanel3.add(libelleCmd, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 83, 425, 31));

        qteCmd.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jPanel3.add(qteCmd, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 131, 425, 30));

        dateCmdTxtH.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        dateCmdTxtH.setText("0000-00-00");
        dateCmdTxtH.setEnabled(false);
        jPanel3.add(dateCmdTxtH, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, 410, 30));

        dateCmd.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        dateCmd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                dateCmdKeyTyped(evt);
            }
        });
        jPanel3.add(dateCmd, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 221, 425, 30));

        tab_Commande.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        tab_Commande.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Commande", "Libellé", "Quantité", "Prix", "Date", "Utilisateur"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tab_Commande);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 366, 969, 180));

        ajtBtn.setBackground(new java.awt.Color(255, 255, 255));
        ajtBtn.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        ajtBtn.setText("Ajouter");
        ajtBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajtBtnActionPerformed(evt);
            }
        });
        jPanel3.add(ajtBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 316, 193, 32));

        cherBtn.setBackground(new java.awt.Color(255, 255, 255));
        cherBtn.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        cherBtn.setText("Chercher");
        cherBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cherBtnActionPerformed(evt);
            }
        });
        jPanel3.add(cherBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 316, 193, 32));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Nom Utilisateur");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 274, -1, -1));

        CmbUtilisateur.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jPanel3.add(CmbUtilisateur, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 270, 430, 29));

        Refresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageProjet/icons8-refresh-35.png"))); // NOI18N
        Refresh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                RefreshMousePressed(evt);
            }
        });
        jPanel3.add(Refresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(476, 316, 44, 32));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1070, 560));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageProjet/bg-5-full.jpg"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 650));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 642, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ajtBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajtBtnActionPerformed
        Connection cn;
        PreparedStatement ps;  
        cn=connecter();
        
       try{
           if (cn==null){
               JOptionPane.showMessageDialog(this, "Pas de connexion");
           }
           else {
                if(IDCmd.getText().equals("") || prixCmd.getText().equals("") ||dateCmd.getText().equals("")|| qteCmd.getText().equals("") || libelleCmd.getText().equals(""))
                {JOptionPane.showMessageDialog(this, "SVP entrer vos donneés"); }
                else{               
           ps = cn.prepareStatement("insert into cammande values(?,?,?,?,?,?)");
           ps.setString(1,IDCmd.getText());
           ps.setString(2,libelleCmd.getText());
           ps.setString(3,qteCmd.getText());
           ps.setString(4,prixCmd.getText());
           ps.setString(5,dateCmd.getText());
           ps.setInt(6,CmbUtilisateur.getSelectedIndex()+1);           
           ps.executeUpdate();
           JOptionPane.showMessageDialog(this, "L'ajout est fait avec succés");
           }}
          }catch(Exception e){
       JOptionPane.showMessageDialog(this, "NULL");
       }
    }//GEN-LAST:event_ajtBtnActionPerformed

    private void cherBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cherBtnActionPerformed
        ArrayList<Commande> listCmd =new ArrayList<>();
        Connection cn;
        PreparedStatement ps;  
        cn=connecter();
        ResultSet rs;
       try{
           if (cn==null){
               JOptionPane.showMessageDialog(this, "Pas de connexion");
           }
           else {
           ps = cn.prepareStatement("select idCommande,libelle,qteCmd,prixCmd,dateCmd,nomUtilisateur from cammande c ,utilisateur u where c.idUtilisateur=u.idUtilisateur order by idCommande asc ");
           rs=ps.executeQuery();
           Commande cmd;
           while(rs.next()){
             cmd=new Commande(rs.getInt("idCommande"),rs.getString("libelle"),rs.getInt("qteCmd"),rs.getInt("prixCmd"),rs.getString("dateCmd"),rs.getString("nomUtilisateur"));
             listCmd.add(cmd);
           }
           }
         }catch(Exception Ex){}
       DefaultTableModel model=(DefaultTableModel) tab_Commande.getModel();
        Object[] row = new Object[6];
      for(int i=0;i<listCmd.size();i++)
      {
          row[0]=listCmd.get(i).getIdCmd();
          row[1]=listCmd.get(i).getLibelleCmd();
          row[2]=listCmd.get(i).getQteCmd();
          row[3]=listCmd.get(i).getPrixCmd();
          row[4]=listCmd.get(i).getDateCmd();
          row[5]=listCmd.get(i).getNomUtilisateur();
          model.addRow(row);
      }
    }//GEN-LAST:event_cherBtnActionPerformed

    private void RefreshMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RefreshMousePressed
        IDCmd.setText(" ");
          libelleCmd.setText(" ");
          qteCmd.setText(" ");
          prixCmd.setText(" ");
          dateCmd.setText(" ");
          CmbUtilisateur.setSelectedIndex(0);
    }//GEN-LAST:event_RefreshMousePressed

    private void dateCmdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dateCmdKeyTyped
     
        if(" ".equals(dateCmd.getText()))
        {
           dateCmdTxtH.setVisible(true);
           dateCmdTxtH.setEnabled(false);
        }
        else
        {
           dateCmdTxtH.setVisible(false);
           dateCmdTxtH.setEnabled(false);
        } 
    }//GEN-LAST:event_dateCmdKeyTyped

    public void RemplirComboUtilisateur(){
        Connection cn;
        PreparedStatement ps;
        cn=connecter();
        try{
            if (cn==null){
                JOptionPane.showMessageDialog(this, "Pas de connexion");
            }
            else {
                ps=cn.prepareStatement("select nomUtilisateur from utilisateur ");
                ResultSet rs=ps.executeQuery();
                while(rs.next())
                {
                CmbUtilisateur.addItem(rs.getString("nomUtilisateur"));
                 }
        }
            }catch(Exception Ex){}
    }
    public Connection connecter(){
     
     String url ="jdbc:mysql://localhost:3306/gestionmagasin?zeroDateTimeBehavior=convertToNull";
     Connection cn;
     String user="root";
     String password="";
        try{
            cn=DriverManager.getConnection(url,user,password);
            return cn;
            
        }catch(Exception Ex){ return null;}
        
 
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Commandes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Commandes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Commandes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Commandes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Commandes().setVisible(true);
            }
         });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox CmbUtilisateur;
    private javax.swing.JTextField IDCmd;
    private javax.swing.JLabel Refresh;
    private javax.swing.JButton ajtBtn;
    private javax.swing.JButton cherBtn;
    private javax.swing.JTextField dateCmd;
    private javax.swing.JLabel dateCmdTxtH;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField libelleCmd;
    private javax.swing.JTextField prixCmd;
    private javax.swing.JTextField qteCmd;
    private javax.swing.JTable tab_Commande;
    // End of variables declaration//GEN-END:variables
}
