/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetfst;

import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.FileOutputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.MessageFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.event.DocumentListener;
import javax.swing.event.UndoableEditListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.Document;
import javax.swing.text.Element;
import javax.swing.text.Position;
import javax.swing.text.Segment;

/**
 *
 * @author Hp
 */
public class Facture extends javax.swing.JFrame {

    /**
     * Creates new form Facture
     */
    public Facture() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        AfficheFacture = new javax.swing.JLabel();
        PrintFacture = new javax.swing.JLabel();
        Total = new javax.swing.JLabel();
        mesFact = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tab_Facture = new javax.swing.JTable();
        NomClient = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("Factures"); // NOI18N

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.darkGray));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AfficheFacture.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageProjet/icons8-search-35.png"))); // NOI18N
        AfficheFacture.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AfficheFacture.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AfficheFactureMouseClicked(evt);
            }
        });
        jPanel1.add(AfficheFacture, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 100, 44, 36));

        PrintFacture.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageProjet/icons8-print-35.png"))); // NOI18N
        PrintFacture.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PrintFacture.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PrintFactureMouseClicked(evt);
            }
        });
        jPanel1.add(PrintFacture, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 100, 44, 36));

        Total.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        Total.setForeground(new java.awt.Color(255, 255, 255));
        Total.setText("Client    :");
        jPanel1.add(Total, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 90, 36));

        mesFact.setBackground(new java.awt.Color(255, 255, 255));
        mesFact.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        mesFact.setForeground(new java.awt.Color(255, 51, 255));
        mesFact.setText("Mes factures");
        mesFact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mesFactActionPerformed(evt);
            }
        });
        jPanel1.add(mesFact, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 100, 193, 36));

        tab_Facture.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID facture", "Produit", "Date facture", "Quantité", "Prix vente", "Total", "Client"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Double.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tab_Facture.setOpaque(false);
        tab_Facture.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab_FactureMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tab_Facture);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 147, 1024, 305));

        NomClient.setFont(new java.awt.Font("Toledo", 1, 14)); // NOI18N
        NomClient.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(NomClient, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, 307, 36));

        jLabel1.setFont(new java.awt.Font("French Script MT", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageProjet/icons8-bill-50.png"))); // NOI18N
        jLabel1.setText("Facturation");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 10, 290, 60));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 1080, 10));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageProjet/icons8-add-35.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel3MousePressed(evt);
            }
        });
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 40, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageProjet/bg-5-full.jpg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 480));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PrintFactureMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PrintFactureMouseClicked
       MessageFormat header = new MessageFormat("Les factures des Clients  ");
       MessageFormat footer = new MessageFormat("Page{0,number,integer}");
 
       try{
        
           boolean print = tab_Facture.print(JTable.PrintMode.NORMAL, header, footer);
        
        }catch(java.awt.print.PrinterException Ex){}

    }//GEN-LAST:event_PrintFactureMouseClicked

    private void AfficheFactureMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AfficheFactureMouseClicked
        Connection cn;
      PreparedStatement ps;
      ResultSet rs;
      ArrayList<FactureClient> listFacture =new ArrayList<>();
      cn=connecter();
      try{
      if (cn==null){
          JOptionPane.showMessageDialog(this, "Pas de connexion");}
          else
          {
            ps=cn.prepareStatement("select f.idFactureClient,p.designation,dateFactureC,qte,prixVente,c.nomClient from factureClient f,client c,vente v,produit p where f.idFactureClient=v.idFactureClient and p.idProduit=v.idProduit and c.idClient=v.idClient  ");
            rs=ps.executeQuery();
            FactureClient factC;
            while(rs.next())
            {
               double total =(rs.getInt("prixVente")*rs.getInt("qte")) ; 
               factC= new FactureClient(rs.getInt("idFactureClient"),rs.getString("designation"),rs.getString("dateFactureC"),rs.getInt("qte"),rs.getInt("prixVente"),total,rs.getString("nomClient"));
               listFacture.add(factC);
            }
         }
      }catch(Exception e)
      {JOptionPane.showMessageDialog(this, e); }
        DefaultTableModel model=(DefaultTableModel) tab_Facture.getModel();
        Object[] row = new Object[8];
      for(int i=0;i<listFacture.size();i++)
      {
          row[0]=listFacture.get(i).getIdFacture();
          row[1]=listFacture.get(i).getIdProduit();
          row[2]=listFacture.get(i).getReference();
          row[3]=listFacture.get(i).getQte();
          row[4]=listFacture.get(i).getPrixVente();
          row[5]=listFacture.get(i).getTotal();
          row[6]=listFacture.get(i).getIdClient();
          model.addRow(row);
      }
    }//GEN-LAST:event_AfficheFactureMouseClicked

    private void mesFactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mesFactActionPerformed
       MesFactures f=new MesFactures();
        f.setVisible(true);
    }//GEN-LAST:event_mesFactActionPerformed

    private void tab_FactureMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab_FactureMouseClicked
        int row = tab_Facture.getSelectedRow();
        TableModel model = tab_Facture.getModel();
        NomClient.setText(model.getValueAt(row,6).toString());

    }//GEN-LAST:event_tab_FactureMouseClicked

    private void jLabel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MousePressed
        CréerFacture NewF=new CréerFacture();
        NewF.setVisible(true);
    }//GEN-LAST:event_jLabel3MousePressed
public Connection connecter(){
     String url ="jdbc:mysql://localhost:3306/gestionmagasin?zeroDateTimeBehavior=convertToNull";
     Connection cn;
     String user="root";
     String password="";
        try{
            cn=DriverManager.getConnection(url,user,password);
            return cn;
            
        }catch(Exception Ex){ return null;}
        
 }



    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Facture.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Facture.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Facture.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Facture.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Facture().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AfficheFacture;
    private javax.swing.JLabel NomClient;
    private javax.swing.JLabel PrintFacture;
    private javax.swing.JLabel Total;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton mesFact;
    private javax.swing.JTable tab_Facture;
    // End of variables declaration//GEN-END:variables
}
