/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetfst;

import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Hp
 */
public class Fournisseurs extends javax.swing.JFrame {

    /**
     * Creates new form Fournisseurs
     */
    public Fournisseurs() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tab_Fournisseur = new javax.swing.JTable();
        AfficherFourn = new javax.swing.JLabel();
        ImprimerFicheTech = new javax.swing.JLabel();
        IDFTxt = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();

        jLabel8.setText("jLabel8");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("Fournisseurs"); // NOI18N

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tab_Fournisseur.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tab_Fournisseur.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID fournisseur", "Nom fournisseur", "Adresse", "Téléphone", "Email"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tab_Fournisseur.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab_FournisseurMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tab_Fournisseur);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 968, 200));

        AfficherFourn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageProjet/icons8-search-35.png"))); // NOI18N
        AfficherFourn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AfficherFourn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AfficherFournMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AfficherFournMouseEntered(evt);
            }
        });
        jPanel1.add(AfficherFourn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 44, 52));

        ImprimerFicheTech.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageProjet/icons8-print-35.png"))); // NOI18N
        ImprimerFicheTech.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ImprimerFicheTech.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ImprimerFicheTechMouseClicked(evt);
            }
        });
        jPanel1.add(ImprimerFicheTech, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 44, 52));

        IDFTxt.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        IDFTxt.setForeground(new java.awt.Color(255, 255, 255));
        IDFTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(IDFTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, 370, 40));

        jLabel1.setFont(new java.awt.Font("French Script MT", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Fournisseurs");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, 288, 50));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 69, 988, 10));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageProjet/bg-5-full.jpg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -6, 990, 360));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ImprimerFicheTechMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ImprimerFicheTechMouseClicked
       if(IDFTxt.getText().equals("Bayer")){
           /* Recuperation de l'environnement */
           Runtime runtime = Runtime.getRuntime(); 
           /* Tableau de parametres : chemin vers l'appli, chemin vers le pdf */
           String[] parametres = new String[]{
           "C:\\Program Files (x86)\\Adobe\\Acrobat Reader DC\\Reader\\AcroRd32.exe", 
           "C:\\Users\\Hp\\Documents\\NetBeansProjects\\ProjetFst\\src\\Fiches Techniques Fournisseurs\\Bayer.pdf"
           };
           /* Execution */
           try {
           runtime.exec(parametres);
           }
           catch(Exception e){
           e.printStackTrace();
           }
       }
       if(IDFTxt.getText().equals("AFRIC CHIMIE ET CONSULTANTS")){
            /* Recuperation de l'environnement */
           Runtime runtime = Runtime.getRuntime(); 
           /* Tableau de parametres : chemin vers l'appli, chemin vers le pdf */
           String[] parametres = new String[]{
           "C:\\Program Files (x86)\\Adobe\\Acrobat Reader DC\\Reader\\AcroRd32.exe", 
           "C:\\Users\\Hp\\Documents\\NetBeansProjects\\ProjetFst\\src\\Fiches Techniques Fournisseurs\\Afric chimie et consultants.pdf"
           };
           /* Execution */
           try {
           runtime.exec(parametres);
           }
           catch(Exception e){
           e.printStackTrace();
           }
       }
       if(IDFTxt.getText().equals("Broychim")){
           /* Recuperation de l'environnement */
           Runtime runtime = Runtime.getRuntime(); 
           /* Tableau de parametres : chemin vers l'appli, chemin vers le pdf */
           String[] parametres = new String[]{
           "C:\\Program Files (x86)\\Adobe\\Acrobat Reader DC\\Reader\\AcroRd32.exe", 
           "C:\\Users\\Hp\\Documents\\NetBeansProjects\\ProjetFst\\src\\Fiches Techniques Fournisseurs\\Broychim.pdf"
           };
           /* Execution */
           try {
           runtime.exec(parametres);
           }
           catch(Exception e){
           e.printStackTrace();
           }
       }
       if(IDFTxt.getText().equals("Cadilhac")){
            /* Recuperation de l'environnement */
           Runtime runtime = Runtime.getRuntime(); 
           /* Tableau de parametres : chemin vers l'appli, chemin vers le pdf */
           String[] parametres = new String[]{
           "C:\\Program Files (x86)\\Adobe\\Acrobat Reader DC\\Reader\\AcroRd32.exe", 
           "C:\\Users\\Hp\\Documents\\NetBeansProjects\\ProjetFst\\src\\Fiches Techniques Fournisseurs\\CADILHAC.pdf"
           };
           /* Execution */
           try {
           runtime.exec(parametres);
           }
           catch(Exception e){
           e.printStackTrace();
           }
       }
       if(IDFTxt.getText().equals("Fortrade")){
           /* Recuperation de l'environnement */
           Runtime runtime = Runtime.getRuntime(); 
           /* Tableau de parametres : chemin vers l'appli, chemin vers le pdf */
           String[] parametres = new String[]{
           "C:\\Program Files (x86)\\Adobe\\Acrobat Reader DC\\Reader\\AcroRd32.exe", 
           "C:\\Users\\Hp\\Documents\\NetBeansProjects\\ProjetFst\\src\\Fiches Techniques Fournisseurs\\Fortrade.pdf"
           };
           /* Execution */
           try {
           runtime.exec(parametres);
           }
           catch(Exception e){
           e.printStackTrace();
           }
       }
       if(IDFTxt.getText().equals("MARJAC")){
            /* Recuperation de l'environnement */
           Runtime runtime = Runtime.getRuntime(); 
           /* Tableau de parametres : chemin vers l'appli, chemin vers le pdf */
           String[] parametres = new String[]{
           "C:\\Program Files (x86)\\Adobe\\Acrobat Reader DC\\Reader\\AcroRd32.exe", 
           "C:\\Users\\Hp\\Documents\\NetBeansProjects\\ProjetFst\\src\\Fiches Techniques Fournisseurs\\MARJAC.pdf"
           };
           /* Execution */
           try {
           runtime.exec(parametres);
           }
           catch(Exception e){
           e.printStackTrace();
           }
       }
       if(IDFTxt.getText().equals("KapaMaroc")){
           /* Recuperation de l'environnement */
           Runtime runtime = Runtime.getRuntime(); 
           /* Tableau de parametres : chemin vers l'appli, chemin vers le pdf */
           String[] parametres = new String[]{
           "C:\\Program Files (x86)\\Adobe\\Acrobat Reader DC\\Reader\\AcroRd32.exe", 
           "C:\\Users\\Hp\\Documents\\NetBeansProjects\\ProjetFst\\src\\Fiches Techniques Fournisseurs\\Kapamaroc.pdf"
           };
           /* Execution */
           try {
           runtime.exec(parametres);
           }
           catch(Exception e){
           e.printStackTrace();
           }
       }
       if(IDFTxt.getText().equals("Alpha Global")){
            /* Recuperation de l'environnement */
           Runtime runtime = Runtime.getRuntime(); 
           /* Tableau de parametres : chemin vers l'appli, chemin vers le pdf */
           String[] parametres = new String[]{
           "C:\\Program Files (x86)\\Adobe\\Acrobat Reader DC\\Reader\\AcroRd32.exe", 
           "C:\\Users\\Hp\\Documents\\NetBeansProjects\\ProjetFst\\src\\Fiches Techniques Fournisseurs\\Alpha.pdf"
           };
           /* Execution */
           try {
           runtime.exec(parametres);
           }
           catch(Exception e){
           e.printStackTrace();
           }
       }
       if(IDFTxt.getText().equals("Sahel equipement")){
            /* Recuperation de l'environnement */
           Runtime runtime = Runtime.getRuntime(); 
           /* Tableau de parametres : chemin vers l'appli, chemin vers le pdf */
           String[] parametres = new String[]{
           "C:\\Program Files (x86)\\Adobe\\Acrobat Reader DC\\Reader\\AcroRd32.exe", 
           "C:\\Users\\Hp\\Documents\\NetBeansProjects\\ProjetFst\\src\\Fiches Techniques Fournisseurs\\SAHEL.pdf"
           };
           /* Execution */
           try {
           runtime.exec(parametres);
           }
           catch(Exception e){
           e.printStackTrace();
           }
       }
       if(IDFTxt.getText().equals("Sakia Computers")){
           /* Recuperation de l'environnement */
           Runtime runtime = Runtime.getRuntime(); 
           /* Tableau de parametres : chemin vers l'appli, chemin vers le pdf */
           String[] parametres = new String[]{
           "C:\\Program Files (x86)\\Adobe\\Acrobat Reader DC\\Reader\\AcroRd32.exe", 
           "C:\\Users\\Hp\\Documents\\NetBeansProjects\\ProjetFst\\src\\Fiches Techniques Fournisseurs\\SAKIA.pdf"
           };
           /* Execution */
           try {
           runtime.exec(parametres);
           }
           catch(Exception e){
           e.printStackTrace();
           }
       }
       if(IDFTxt.getText().equals("GUY HOQUET CASABLANCA")){
            /* Recuperation de l'environnement */
           Runtime runtime = Runtime.getRuntime(); 
           /* Tableau de parametres : chemin vers l'appli, chemin vers le pdf */
           String[] parametres = new String[]{
           "C:\\Program Files (x86)\\Adobe\\Acrobat Reader DC\\Reader\\AcroRd32.exe", 
           "C:\\Users\\Hp\\Documents\\NetBeansProjects\\ProjetFst\\src\\Fiches Techniques Fournisseurs\\GUY HOQUET CASABLANCA.pdf"
           };
           /* Execution */
           try {
           runtime.exec(parametres);
           }
           catch(Exception e){
           e.printStackTrace();
           }
       }
    }//GEN-LAST:event_ImprimerFicheTechMouseClicked

    private void AfficherFournMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AfficherFournMouseClicked
      
        Connection cn;
        PreparedStatement ps;
        ResultSet rs;
        ArrayList<Fournisseur> listFourn =new ArrayList<>();
        cn=connecter();
        try{
            if (cn==null){
                JOptionPane.showMessageDialog(this, "Pas de connexion");}
            else
            {
                ps=cn.prepareStatement("select * from fournisseur ");
                rs=ps.executeQuery();
                
                while(rs.next())
                {
                  Fournisseur fr= new Fournisseur(rs.getInt("idFournisseur"),rs.getString("nomFournisseur"),rs.getString("adresseFournisseur"),rs.getString("telFournisseur"),rs.getString("mailFournisseur"));
                  listFourn.add(fr);
                }
            }
        }catch(Exception e)
        {JOptionPane.showMessageDialog(this, "il existe une erreur"); }
        DefaultTableModel model=(DefaultTableModel) tab_Fournisseur.getModel();
        Object[] row = new Object[5];
        for(int i=0;i<listFourn.size();i++)
        {
            row[0]=listFourn.get(i).getIdFournisseur();
            row[1]=listFourn.get(i).getNomFournisseur();
            row[2]=listFourn.get(i).getAdresseFournisseur();
            row[3]=listFourn.get(i).getTelFournisseur();
            row[4]=listFourn.get(i).getMailFournisseur();
            model.addRow(row);
        }
    }//GEN-LAST:event_AfficherFournMouseClicked

    private void AfficherFournMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AfficherFournMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_AfficherFournMouseEntered

    private void tab_FournisseurMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab_FournisseurMouseClicked
        int row = tab_Fournisseur.getSelectedRow();
        TableModel model = tab_Fournisseur.getModel();
        IDFTxt.setText(model.getValueAt(row,1).toString());
    }//GEN-LAST:event_tab_FournisseurMouseClicked
 public Connection connecter(){
     String url ="jdbc:mysql://localhost:3306/gestionmagasin?zeroDateTimeBehavior=convertToNull";
     Connection cn;
     String user="root";
     String password="";
        try{
            cn=DriverManager.getConnection(url,user,password);
            return cn;
            
        }catch(Exception Ex){ return null;}
        
 }
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fournisseurs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fournisseurs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fournisseurs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fournisseurs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fournisseurs().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AfficherFourn;
    private javax.swing.JLabel IDFTxt;
    private javax.swing.JLabel ImprimerFicheTech;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tab_Fournisseur;
    // End of variables declaration//GEN-END:variables
}
