/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetfst;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Hp
 */
public class LoginForm extends javax.swing.JFrame {

    /**
     * Creates new form LoginForm
     */
    public LoginForm() {
        initComponents();
        
        
    }
 public Connection connecter(){
     String url ="jdbc:mysql://localhost:3306/gestionmagasin?zeroDateTimeBehavior=convertToNull";
     Connection cn;
     String user="root";
     String password="";
        try{
            cn=DriverManager.getConnection(url,user,password);
            return cn;
            
        }catch(Exception Ex){ return null;}
     
 }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        PasswordOublier = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        TextHolder = new javax.swing.JLabel();
        textHolderPass = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setModalExclusionType(null);
        setName("LoginForm"); // NOI18N
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 16)); // NOI18N
        jButton1.setText("Exit");
        jButton1.setOpaque(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(590, 300, 230, 40);

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 16)); // NOI18N
        jButton2.setText("Login");
        jButton2.setOpaque(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(210, 300, 240, 40);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageProjet/icons8-password-30.png"))); // NOI18N
        jLabel2.setText("Password");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(120, 210, 120, 30);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageProjet/icons8-name-30.png"))); // NOI18N
        jLabel3.setText("Username");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(120, 160, 130, 30);

        LoginTxt.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        LoginTxt.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        LoginTxt.setBorder(null);
        LoginTxt.setOpaque(false);
        LoginTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginTxtActionPerformed(evt);
            }
        });
        LoginTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                LoginTxtKeyTyped(evt);
            }
        });
        jPanel1.add(LoginTxt);
        LoginTxt.setBounds(330, 160, 420, 30);

        PasswordOublier.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        PasswordOublier.setText("Mot de passe oublier ?");
        PasswordOublier.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PasswordOublier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PasswordOublierMouseClicked(evt);
            }
        });
        jPanel1.add(PasswordOublier);
        PasswordOublier.setBounds(330, 260, 140, 20);

        jLabel5.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        jLabel5.setText("Créer nouveau compte ");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel5);
        jLabel5.setBounds(590, 260, 160, 20);

        PasswordAd.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        PasswordAd.setBorder(null);
        PasswordAd.setOpaque(false);
        PasswordAd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                PasswordAdKeyTyped(evt);
            }
        });
        jPanel1.add(PasswordAd);
        PasswordAd.setBounds(330, 210, 420, 30);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(330, 240, 420, 10);
        jPanel1.add(jSeparator2);
        jSeparator2.setBounds(330, 190, 420, 10);

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Hp\\Desktop\\entete-interne_MET.jpg")); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(0, 10, 940, 120);

        TextHolder.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        TextHolder.setText("Entrer le nom d'utilisateur");
        TextHolder.setEnabled(false);
        jPanel1.add(TextHolder);
        TextHolder.setBounds(330, 154, 310, 40);

        textHolderPass.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        textHolderPass.setText("Entrer le mot de passe");
        textHolderPass.setEnabled(false);
        jPanel1.add(textHolderPass);
        textHolderPass.setBounds(330, 204, 360, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Hp\\Downloads\\6906.jpg")); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 940, 360);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 936, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

 
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Connection cn;
        cn = connecter();
        try {
            if (LoginTxt.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(this, "Entrer les informations nécessaires ");
            } else {
                String query = "select * from utilisateur where userName =? and password=?";;
                PreparedStatement pst = cn.prepareStatement(query);
                pst.setString(1, LoginTxt.getText());
                pst.setString(2, PasswordAd.getText());
                ResultSet rs = pst.executeQuery();
                while (rs.next()) {
                    String NomComplet = (rs.getString("nomUtilisateur") + " " + rs.getString("prenomUtilisateur"));
                    InterfacePrincipal ip = new InterfacePrincipal();
                    InterfacePrincipal.NewSession.setText(NomComplet);
                    ip.setVisible(true);
                    this.dispose();

                }
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "le nom utilisateur ou le mot de passe est incorrect");

        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void LoginTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LoginTxtActionPerformed

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked

NewCompte NCPT=new NewCompte();
NCPT.setVisible(true);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void PasswordOublierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PasswordOublierMouseClicked
        ChangerPassword cp =new ChangerPassword();
        cp.setVisible(true);
        
    }//GEN-LAST:event_PasswordOublierMouseClicked

    private void LoginTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LoginTxtKeyTyped
      
        if(" ".equals(LoginTxt.getText()))
        {
           TextHolder.setVisible(true);
           TextHolder.setEnabled(false);
        }
        else
        {
           TextHolder.setVisible(false);
           TextHolder.setEnabled(false);
        } 

    }//GEN-LAST:event_LoginTxtKeyTyped

    private void PasswordAdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PasswordAdKeyTyped

        if(" ".equals(PasswordAd.getText()))
        {
           textHolderPass.setVisible(true);
           textHolderPass.setEnabled(false);
        }
        else
        {
           textHolderPass.setVisible(false);
           textHolderPass.setEnabled(false);
        } 
    }//GEN-LAST:event_PasswordAdKeyTyped

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginForm().setVisible(true);
                 
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static final javax.swing.JTextField LoginTxt = new javax.swing.JTextField();
    public static final javax.swing.JPasswordField PasswordAd = new javax.swing.JPasswordField();
    private javax.swing.JLabel PasswordOublier;
    private javax.swing.JLabel TextHolder;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel textHolderPass;
    // End of variables declaration//GEN-END:variables
}
