/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetfst;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Hp
 */
public class MesFactures extends javax.swing.JFrame {

    /**
     * Creates new form MesFactures
     */
    public MesFactures() {
        initComponents();
        RemplirComboIDCommande();
        RemplirComboUtilisateur();
    }
public void RemplirComboUtilisateur(){
        Connection cn;
        PreparedStatement ps;
        cn=connecter();
        try{
            if (cn==null){
                JOptionPane.showMessageDialog(this, "Pas de connexion");
            }
            else {
                ps=cn.prepareStatement("select nomUtilisateur from utilisateur ");
                ResultSet rs=ps.executeQuery();
                while(rs.next())
                {
                CmbUtilisateur.addItem(rs.getString("nomUtilisateur"));
                 }
        }
            }catch(Exception Ex){}
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        IDfact = new javax.swing.JTextField();
        dateFact = new javax.swing.JTextField();
        libelleFact = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tab_MesFactures = new javax.swing.JTable();
        AjouterFacture = new javax.swing.JLabel();
        CmbIDCmd = new javax.swing.JComboBox();
        viderText = new javax.swing.JLabel();
        AfficherFact = new javax.swing.JLabel();
        CmbUtilisateur = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("Mes factures"); // NOI18N

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Papyrus", 1, 26)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Mes factures ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 15, 199, 31));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 52, 1021, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ID Facture ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 95, 99, 21));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Libellé Facture ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 100, 99, 23));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Date Facture ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 151, 99, 25));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("ID commande");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 150, 99, 25));

        IDfact.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jPanel1.add(IDfact, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 91, 292, 30));

        dateFact.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jPanel1.add(dateFact, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 149, 292, 30));

        libelleFact.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jPanel1.add(libelleFact, new org.netbeans.lib.awtextra.AbsoluteConstraints(719, 91, 292, 30));

        tab_MesFactures.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        tab_MesFactures.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID facture", "Libelle Facture", "Date Facture", "Total", "Utilisateur"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tab_MesFactures);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 251, 984, 146));

        AjouterFacture.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageProjet/icons8-add-35.png"))); // NOI18N
        AjouterFacture.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AjouterFacture.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AjouterFactureMouseClicked(evt);
            }
        });
        jPanel1.add(AjouterFacture, new org.netbeans.lib.awtextra.AbsoluteConstraints(923, 11, -1, -1));

        CmbIDCmd.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        CmbIDCmd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CmbIDCmdMouseClicked(evt);
            }
        });
        jPanel1.add(CmbIDCmd, new org.netbeans.lib.awtextra.AbsoluteConstraints(719, 148, 292, 30));

        viderText.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageProjet/icons8-broom-35.png"))); // NOI18N
        viderText.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        viderText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viderTextMouseClicked(evt);
            }
        });
        jPanel1.add(viderText, new org.netbeans.lib.awtextra.AbsoluteConstraints(976, 11, -1, -1));

        AfficherFact.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageProjet/icons8-search-35.png"))); // NOI18N
        AfficherFact.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AfficherFact.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AfficherFactMouseClicked(evt);
            }
        });
        jPanel1.add(AfficherFact, new org.netbeans.lib.awtextra.AbsoluteConstraints(878, 11, -1, -1));

        CmbUtilisateur.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jPanel1.add(CmbUtilisateur, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 197, 292, 30));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Utilisateur");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 200, 99, 25));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageProjet/bg-5-full.jpg"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(-6, -6, 1030, 420));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AjouterFactureMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AjouterFactureMouseClicked

        Connection cn;
        PreparedStatement ps;
        cn=connecter();

        try{
            if (cn==null){
                JOptionPane.showMessageDialog(this, "Pas de connexion");
            }
            else {
                ps = cn.prepareStatement("insert into facture values(?,?,?,?,?)");
                ps.setString(1,IDfact.getText());
                ps.setString(2,libelleFact.getText());
                ps.setString(3,dateFact.getText());
                ps.setInt(4,CmbIDCmd.getSelectedIndex()+1);
                ps.setInt(5,CmbUtilisateur.getSelectedIndex()+1); 
                ps.executeUpdate();
                JOptionPane.showMessageDialog(this, "L'ajout est fait avec succés");
            }}catch(Exception e){
                JOptionPane.showMessageDialog(this, e);
            }
    }//GEN-LAST:event_AjouterFactureMouseClicked

    private void AfficherFactMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AfficherFactMouseClicked
 Connection cn;
      PreparedStatement ps;
      ResultSet rs;
      ArrayList<MaFacture> listFact =new ArrayList<>();
      cn=connecter();
      try{
      if (cn==null){
          JOptionPane.showMessageDialog(this, "Pas de connexion");}
          else
          {
            ps=cn.prepareStatement("select idFacture,libelleFacture,dateFacture,prixCmd,qteCmd,nomUtilisateur from facture f,cammande c,utilisateur u where f.idCommande=c.idCommande and f.idUtilisateur=u.idUtilisateur ");
            rs=ps.executeQuery();
            MaFacture fact;
            while(rs.next())
            {
               double total =(rs.getInt("prixCmd")*rs.getInt("qteCmd")) ; 
               fact= new MaFacture(rs.getInt("idFacture"),rs.getString("libelleFacture"),rs.getString("dateFacture"),total,rs.getString("nomUtilisateur"));
               listFact.add(fact);
            }
         }
      }catch(Exception e)
      {JOptionPane.showMessageDialog(this, "il existe une erreur"); }
        DefaultTableModel model=(DefaultTableModel) tab_MesFactures.getModel();
        Object[] row = new Object[6];
      for(int i=0;i<listFact.size();i++)
      {
          row[0]=listFact.get(i).getIdFacture();
          row[1]=listFact.get(i).getLibelleFacture();
          row[2]=listFact.get(i).getDateFacture(); 
          row[3]=listFact.get(i).getTotal();
          row[4]=listFact.get(i).getNomUtilisateur();
          model.addRow(row);
      }

    }//GEN-LAST:event_AfficherFactMouseClicked

    private void viderTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viderTextMouseClicked

        IDfact.setText(" ");
        libelleFact.setText(" ");
        dateFact.setText(" ");
        CmbIDCmd.setSelectedIndex(0);
         DefaultTableModel model =(DefaultTableModel) tab_MesFactures.getModel();
         model.setRowCount(0);
    
    }//GEN-LAST:event_viderTextMouseClicked

    private void CmbIDCmdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CmbIDCmdMouseClicked
 Connection cn;
        PreparedStatement ps;
        cn=connecter();
        try{
            if (cn==null){
                JOptionPane.showMessageDialog(this, "Pas de connexion");
            }
            else {
                ps=cn.prepareStatement("select dateCmd from cammande where idCommande="+CmbIDCmd.getSelectedItem());
                ResultSet rs=ps.executeQuery();
                while(rs.next())
                {
                    dateFact.setText(rs.getString("dateCmd"));
                   
                }
            }
        }catch(Exception Ex){}    }//GEN-LAST:event_CmbIDCmdMouseClicked

     public Connection connecter(){
     
     String url ="jdbc:mysql://localhost:3306/gestionmagasin?zeroDateTimeBehavior=convertToNull";
     Connection cn;
     String user="root";
     String password="";
        try{
            cn=DriverManager.getConnection(url,user,password);
            return cn;
            
        }catch(Exception Ex){ return null;}
        
 }
    public void RemplirComboIDCommande(){
        Connection cn;
        PreparedStatement ps;
        cn=connecter();
        try{
            if (cn==null){
                JOptionPane.showMessageDialog(this, "Pas de connexion");
            }
            else {
                ps=cn.prepareStatement("select idCommande from cammande order by idCommande asc ");
                ResultSet rs=ps.executeQuery();
                while(rs.next())
                {
                CmbIDCmd.addItem(rs.getInt("idCommande"));
                 }
        }
            }catch(Exception Ex){}
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MesFactures.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MesFactures.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MesFactures.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MesFactures.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MesFactures().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AfficherFact;
    private javax.swing.JLabel AjouterFacture;
    private javax.swing.JComboBox CmbIDCmd;
    private javax.swing.JComboBox CmbUtilisateur;
    private javax.swing.JTextField IDfact;
    private javax.swing.JTextField dateFact;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField libelleFact;
    private javax.swing.JTable tab_MesFactures;
    private javax.swing.JLabel viderText;
    // End of variables declaration//GEN-END:variables
}
