/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetfst;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/**
 *
 * @author Hp
 */
public class NewFacture extends javax.swing.JFrame {

    /**
     * Creates new form NewFacture
     */
    public NewFacture() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        IdFacture = new javax.swing.JTextField();
        DateFacture = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        CreateFacture = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.darkGray, java.awt.Color.black));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 71, 592, 10));

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageProjet/icons8-create-50.png"))); // NOI18N
        jLabel1.setText("Nouveau facture");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 13, 242, 52));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("ID facture");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 121, 79, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Date facture");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 164, 79, 33));

        IdFacture.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        IdFacture.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IdFactureActionPerformed(evt);
            }
        });
        jPanel1.add(IdFacture, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 355, 33));

        DateFacture.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        DateFacture.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DateFactureActionPerformed(evt);
            }
        });
        jPanel1.add(DateFacture, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 164, 355, 34));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.black));

        CreateFacture.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        CreateFacture.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageProjet/icons8-add-35.png"))); // NOI18N
        CreateFacture.setText("    Créer");
        CreateFacture.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CreateFactureMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CreateFacture, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CreateFacture, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 210, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IdFactureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdFactureActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IdFactureActionPerformed

    private void DateFactureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DateFactureActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DateFactureActionPerformed
public Connection connecter(){
     
     String url ="jdbc:mysql://localhost:3306/gestionmagasin?zeroDateTimeBehavior=convertToNull";
     Connection cn;
     String user="root";
     String password="";
        try{
            cn=DriverManager.getConnection(url,user,password);
            return cn;
            
        }catch(Exception Ex){ return null;}
        
 }
    private void CreateFactureMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CreateFactureMousePressed
         Connection cn;
        PreparedStatement ps;
        cn=connecter();
        try{
            if (cn==null){
                JOptionPane.showMessageDialog(this, "Pas de connexion");
            }
            else {
                if(IdFacture.getText().equals("") || DateFacture.getText().equals(""))
                {JOptionPane.showMessageDialog(this, "SVP entrer vos donneé"); }
                else{
                    ps = cn.prepareStatement("insert into FactureClient(idFactureClient,dateFactureC) values(?,?)");
                    ps.setString(1,IdFacture.getText());
                    ps.setString(2,DateFacture.getText());
                     ps.executeUpdate();
                    JOptionPane.showMessageDialog(this, "L'Ajout est fait avec succés");
                }
            }}catch(Exception Ex){}
    }//GEN-LAST:event_CreateFactureMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewFacture.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewFacture.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewFacture.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewFacture.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewFacture().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CreateFacture;
    private javax.swing.JTextField DateFacture;
    private javax.swing.JTextField IdFacture;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
