/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetfst;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import projetfst.Fournisseur;
import projetfst.Stock;
/**
 *
 * @author Hp
 */
public class Produit extends javax.swing.JFrame {

    /**
     * Creates new form Produit
     */
    public Produit() {
        initComponents();
        RemplirComboStock();
        RemplirComboFournisseur();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        ComboStock = new javax.swing.JComboBox();
        IDProdTxt = new javax.swing.JTextField();
        DesignationTxt = new javax.swing.JTextField();
        RéferenceTxt = new javax.swing.JTextField();
        PrixTxt = new javax.swing.JTextField();
        RemiseTxt = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        AjouterProduit = new javax.swing.JButton();
        SupprimerProduit = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        ChercherTxt = new javax.swing.JTextField();
        ChercherProduit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tab_Produit = new javax.swing.JTable();
        ComboFourn = new javax.swing.JComboBox();
        QteSTxt = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Produits");
        setName("Produits"); // NOI18N

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 93, 936, -1));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 35, 940, -1));

        jLabel1.setFont(new java.awt.Font("French Script MT", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Produits");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 40, 340, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageProjet/icons8-product-50.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 37, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ID Produit");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 139, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Réference");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 191, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Designation");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 236, -1, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Fournisseur");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 334, -1, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Quantité ");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 480, -1, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Prix");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 380, -1, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Stock");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 285, -1, -1));

        ComboStock.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jPanel1.add(ComboStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 279, 427, 28));

        IDProdTxt.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel1.add(IDProdTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 133, 427, 31));

        DesignationTxt.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel1.add(DesignationTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 230, 427, 31));

        RéferenceTxt.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel1.add(RéferenceTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 185, 427, 31));

        PrixTxt.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel1.add(PrixTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 374, 427, 31));

        RemiseTxt.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel1.add(RemiseTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 420, 427, 31));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setOpaque(false);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jButton1.setText("Nouveau");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        AjouterProduit.setBackground(new java.awt.Color(255, 255, 255));
        AjouterProduit.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        AjouterProduit.setText("Ajouter");
        AjouterProduit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AjouterProduitActionPerformed(evt);
            }
        });

        SupprimerProduit.setBackground(new java.awt.Color(255, 255, 255));
        SupprimerProduit.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        SupprimerProduit.setText("Supprimer");
        SupprimerProduit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SupprimerProduitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SupprimerProduit, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AjouterProduit, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(AjouterProduit, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(SupprimerProduit, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(715, 133, -1, -1));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Chercher", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel5.setOpaque(false);

        ChercherProduit.setBackground(new java.awt.Color(255, 255, 255));
        ChercherProduit.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        ChercherProduit.setText("Chercher");
        ChercherProduit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChercherProduitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(175, Short.MAX_VALUE)
                .addComponent(ChercherTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addComponent(ChercherProduit, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 4, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ChercherTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ChercherProduit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(15, 15, 15))
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 520, 936, -1));

        tab_Produit.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Produit", "Réference", "Designation", "Stock", "Quantité Stock", "Fournisseur", "Remise", "Prix"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tab_Produit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab_ProduitMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tab_Produit);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 620, 936, 120));

        ComboFourn.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jPanel1.add(ComboFourn, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 328, 427, 28));

        QteSTxt.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel1.add(QteSTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 470, 427, 31));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Remise");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 430, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageProjet/bg-5-full.jpg"))); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -6, 1030, 760));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        IDProdTxt.setText("");
        PrixTxt.setText("");
        RemiseTxt.setText("");
        RéferenceTxt.setText("");
        DesignationTxt.setText("");
        QteSTxt.setText("");
        ComboFourn.setSelectedIndex(0);
        ComboStock.setSelectedIndex(0);
        DefaultTableModel model =(DefaultTableModel) tab_Produit.getModel();
        model.setRowCount(0);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void AjouterProduitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AjouterProduitActionPerformed
        Connection cn;
        PreparedStatement ps;
        cn=connecter();
        try{
            if (cn==null){
                JOptionPane.showMessageDialog(this, "Pas de connexion");
            }
            else {
                if(IDProdTxt.getText().equals("") || RéferenceTxt.getText().equals("") ||DesignationTxt.getText().equals("") || RemiseTxt.getText().equals("") || PrixTxt.getText().equals("") || QteSTxt.getText().equals("") )
                {JOptionPane.showMessageDialog(this, "SVP entrer vos donneé"); }
                else{
                ps = cn.prepareStatement("insert into produit values(?,?,?,?,?,?,?,?,?,?)");
                ps.setString(1,IDProdTxt.getText());
                ps.setString(2,RéferenceTxt.getText());
                ps.setString(3,DesignationTxt.getText());
                ps.setString(4,ComboStock.getSelectedItem().toString());
                ps.setString(5,ComboFourn.getSelectedItem().toString());
                ps.setString(6,RemiseTxt.getText());
                ps.setString(7,PrixTxt.getText());
                ps.setInt(8,ComboStock.getSelectedIndex()+1);
                ps.setInt(9,ComboFourn.getSelectedIndex()+1);
                ps.setString(10,QteSTxt.getText());
                ps.executeUpdate();
                ModifierStock();
                JOptionPane.showMessageDialog(this, "L'ajout est fait avec succés");
                }}}catch(Exception e){
                JOptionPane.showMessageDialog(this, e);
    }//GEN-LAST:event_AjouterProduitActionPerformed
    }
    
    private void SupprimerProduitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SupprimerProduitActionPerformed
        Connection cn;
        PreparedStatement ps;
        cn=connecter();
        try{
            if (cn==null){
                JOptionPane.showMessageDialog(this, "Pas de connexion");
            }
            else {
                int row = tab_Produit.getSelectedRow();
                String value = (tab_Produit.getModel().getValueAt(row, 6).toString());
                ps = cn.prepareStatement("delete from produit where idProduit="+value);
                ps.executeUpdate();
                JOptionPane.showMessageDialog(this, "La suppression est fait avec succés");
                ActualiserStock();
            }}catch(Exception e){
                JOptionPane.showMessageDialog(this, "NULL");
            }
    }//GEN-LAST:event_SupprimerProduitActionPerformed

    private void ChercherProduitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChercherProduitActionPerformed
        Connection cn;
        PreparedStatement ps;
        ResultSet rs;
        ArrayList<Products> listProduit =new ArrayList<>();
        cn=connecter();
        try{
            if (cn==null){
                JOptionPane.showMessageDialog(this, "Pas de connexion");}
            else
            {
                
                ps=cn.prepareStatement("select idProduit,reference,designation,s.libelle,qteProduitStock,nomFournisseur,remise,prix from Produit p,stock s ,fournisseur f where p.idStock=s.idStock and p.idFournisseur=f.idFournisseur and reference like '%"+ChercherTxt.getText()+"%' ORDER BY p.idProduit ASC ");
                rs=ps.executeQuery();
                Products produit;
                while(rs.next())
                {
          
                 produit= new Products(rs.getInt("idProduit"),rs.getString("reference"),rs.getString("designation"),rs.getString("libelle"),rs.getInt("qteProduitStock"),rs.getString("nomFournisseur"),rs.getInt("remise"),rs.getInt("prix"));
                 listProduit.add(produit);
                }
            }
        }catch(Exception e)
        {JOptionPane.showMessageDialog(this, e); }
        DefaultTableModel model=(DefaultTableModel) tab_Produit.getModel();
        Object[] row = new Object[8];
        for(int i=0;i<listProduit.size();i++)
        {
            row[0]=listProduit.get(i).getIdProduit();
            row[1]=listProduit.get(i).getReferenceProduit();
            row[2]=listProduit.get(i).getDesignationProduit();
            row[3]=listProduit.get(i).getS();
            row[4]=listProduit.get(i).getQte();
            row[5]=listProduit.get(i).getF();
            row[6]=listProduit.get(i).getRemise();
            row[7]=listProduit.get(i).getPrix();
            model.addRow(row);
        }
    }//GEN-LAST:event_ChercherProduitActionPerformed

    private void tab_ProduitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab_ProduitMouseClicked
        int row = tab_Produit.getSelectedRow();
        TableModel model = tab_Produit.getModel();
        IDProdTxt.setText(model.getValueAt(row,0).toString());
        RéferenceTxt.setText(model.getValueAt(row,1).toString());
        DesignationTxt.setText(model.getValueAt(row,2).toString());
        ComboFourn.setSelectedItem(model.getValueAt(row,5).toString());
        PrixTxt.setText(model.getValueAt(row,7).toString());
        RemiseTxt.setText(model.getValueAt(row,6).toString());
        QteSTxt.setText(model.getValueAt(row,4).toString());
        ComboStock.setSelectedItem(model.getValueAt(row,3).toString());
    }//GEN-LAST:event_tab_ProduitMouseClicked
    public void RemplirComboStock(){
        Connection cn;
        PreparedStatement ps;
        cn=connecter();
        try{
            if (cn==null){
                JOptionPane.showMessageDialog(this, "Pas de connexion");
            }
            else {
                ps=cn.prepareStatement("select * from stock ");
                ResultSet rs=ps.executeQuery();
                while(rs.next())
                {
                ComboStock.addItem(rs.getString("libelle"));
                 }
        }
            }catch(Exception Ex){}
    }
    public void RemplirComboFournisseur(){
        Connection cn;
        PreparedStatement ps;
        cn=connecter();
        try{
            if (cn==null){
                JOptionPane.showMessageDialog(this, "Pas de connexion");
            }
            else {
                ps=cn.prepareStatement("select * from fournisseur");
                ResultSet rs=ps.executeQuery();
                while(rs.next())
                {
                ComboFourn.addItem(rs.getString("nomFournisseur"));
                 }
        }
            }catch(Exception Ex){}
    }
    
    public void ModifierStock(){
        Connection cn;
        PreparedStatement ps;
        cn=connecter();
        int qteStock = 0;
        try{
            if (cn==null){
                JOptionPane.showMessageDialog(this, "Pas de connexion");
            }
            else {
                 ps=cn.prepareStatement("select nbrProduit  from Stock s ,produit p  where s.idStock=p.idStock and p.idProduit="+IDProdTxt.getText());
                ResultSet rs=ps.executeQuery();
                while(rs.next())
                {
                 qteStock=rs.getInt("nbrProduit");
                 }  
                 int now=qteStock+Integer.parseInt(QteSTxt.getText());
                  ps =cn.prepareStatement("UPDATE produit,stock SET nbrProduit="+now +" where produit.idStock=stock.idstock and idProduit="+IDProdTxt.getText());
                  ps.executeUpdate();
        }
            }catch(Exception Ex){}  
    }
    
    public void ActualiserStock() {
       Connection cn;
        PreparedStatement ps;
        cn=connecter();
         int   qtePrdAct = 0,qteStock = 0;
        try{
            if (cn==null){
                JOptionPane.showMessageDialog(this, "Pas de connexion");
            }
            else {
     
                ps=cn.prepareStatement("select nbrProduit ,qte from Stock s ,produit p ,vente v where s.idStock=p.idStock and v.idProduit=p.idProduit and v.idProduit="+IDProdTxt.getText());
                ResultSet rs=ps.executeQuery();
                while(rs.next())
                {
                  qtePrdAct =rs.getInt("qte");
                  qteStock=rs.getInt("nbrProduit");
                 }  
                  int now =qteStock - qtePrdAct ;
                  ps =cn.prepareStatement("UPDATE produit,stock SET nbrProduit="+now +" where produit.idStock=stock.idstock and idProduit="+IDProdTxt.getText());
                  ps.executeUpdate();
        }
            }catch(Exception Ex){ } 
    }
    /**
     * @param args the command line arguments
     */
     public Connection connecter(){
     
      String url ="jdbc:mysql://localhost:3306/gestionmagasin?zeroDateTimeBehavior=convertToNull";
     Connection cn;
     String user="root";
     String password="";
        try{
            cn=DriverManager.getConnection(url,user,password);
            return cn;
            
        }catch(Exception Ex){ return null;}
        
 }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Produit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Produit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Produit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Produit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Produit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AjouterProduit;
    private javax.swing.JButton ChercherProduit;
    private javax.swing.JTextField ChercherTxt;
    private javax.swing.JComboBox ComboFourn;
    private javax.swing.JComboBox ComboStock;
    private javax.swing.JTextField DesignationTxt;
    private javax.swing.JTextField IDProdTxt;
    private javax.swing.JTextField PrixTxt;
    private javax.swing.JTextField QteSTxt;
    private javax.swing.JTextField RemiseTxt;
    private javax.swing.JTextField RéferenceTxt;
    private javax.swing.JButton SupprimerProduit;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable tab_Produit;
    // End of variables declaration//GEN-END:variables
}
