/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetfst;

import projetfst.Users;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Hp
 */
public class Utilisateurs extends javax.swing.JFrame {
    
  public Utilisateurs() {
        initComponents(); 
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tab_Utilisateur = new javax.swing.JTable();
        UpdateBtn = new javax.swing.JButton();
        AfficherBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        NomTxt = new javax.swing.JTextField();
        PrenomTxt = new javax.swing.JTextField();
        IDTxt = new javax.swing.JTextField();
        MailTxt = new javax.swing.JTextField();
        PasswordTxt = new javax.swing.JPasswordField();
        SuppBtn = new javax.swing.JButton();
        NewBtn = new javax.swing.JButton();
        TelTxt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        Refresh = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("Utilisateurs"); // NOI18N

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("French Script MT", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageProjet/icons8-user-account-50.png"))); // NOI18N
        jLabel1.setText("Utilisateurs");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 11, 310, 47));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 64, 910, 10));

        tab_Utilisateur.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        tab_Utilisateur.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID utilisateur", "Nom utilisateur", "Prénom utilisateur", "Mail", "Tel", "Password"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tab_Utilisateur.setToolTipText("");
        tab_Utilisateur.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab_UtilisateurMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tab_Utilisateur);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 109, 857, 127));

        UpdateBtn.setBackground(new java.awt.Color(255, 255, 255));
        UpdateBtn.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        UpdateBtn.setText("Modifier");
        UpdateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateBtnActionPerformed(evt);
            }
        });
        jPanel2.add(UpdateBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 254, 122, -1));

        AfficherBtn.setBackground(new java.awt.Color(255, 255, 255));
        AfficherBtn.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        AfficherBtn.setText("Afficher");
        AfficherBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AfficherBtnActionPerformed(evt);
            }
        });
        jPanel2.add(AfficherBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 254, 122, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nom utilisateur");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 379, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Prénom utilisateur");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 424, 122, 26));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("ID utilisateur");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 324, -1, 38));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Mail");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 478, 41, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Password");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 558, 70, -1));

        NomTxt.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jPanel2.add(NomTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 373, 393, 30));

        PrenomTxt.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jPanel2.add(PrenomTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 420, 393, 30));

        IDTxt.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jPanel2.add(IDTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 329, 393, 30));

        MailTxt.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jPanel2.add(MailTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 460, 393, 32));

        PasswordTxt.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jPanel2.add(PasswordTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 552, 393, 30));

        SuppBtn.setBackground(new java.awt.Color(255, 255, 255));
        SuppBtn.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        SuppBtn.setText("Supprimer");
        SuppBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SuppBtnActionPerformed(evt);
            }
        });
        jPanel2.add(SuppBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(441, 254, 122, -1));

        NewBtn.setBackground(new java.awt.Color(255, 255, 255));
        NewBtn.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        NewBtn.setText("Nouveau");
        NewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewBtnActionPerformed(evt);
            }
        });
        jPanel2.add(NewBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(301, 254, 122, -1));

        TelTxt.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jPanel2.add(TelTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 500, 393, 32));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Tel");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 516, 41, -1));

        Refresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageProjet/icons8-refresh-35.png"))); // NOI18N
        Refresh.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Refresh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RefreshMouseClicked(evt);
            }
        });
        jPanel2.add(Refresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 250, 64, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageProjet/bg-5-full.jpg"))); // NOI18N
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 620));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UpdateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateBtnActionPerformed
      Connection cn;
      PreparedStatement ps;
      cn=connecter();
      ArrayList<Users> listUser =new ArrayList<>();
       try{
      if (cn==null){
          JOptionPane.showMessageDialog(this, "Pas de connexion");}
          else
          {  
            int row = tab_Utilisateur.getSelectedRow();
            String value = (tab_Utilisateur.getModel().getValueAt(row, 0).toString());
            ps=cn.prepareStatement("update utilisateur set nomUtilisateur=?,prenomUtilisateur=?,mailUtilisateur=?,telUtilisateur=? where idUtilisateur="+value );
            ps.setString(1, NomTxt.getText());
            ps.setString(2, PrenomTxt.getText());
            ps.setString(3, MailTxt.getText());
            ps.setString(4, TelTxt.getText());
            ps.executeUpdate();
            JOptionPane.showMessageDialog(this, "la modification est bien fait");
          }
      }catch(Exception e)
      {JOptionPane.showMessageDialog(this, e); }
    }//GEN-LAST:event_UpdateBtnActionPerformed

    private void SuppBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SuppBtnActionPerformed
      Connection cn;
      PreparedStatement ps;
      cn=connecter();
      ArrayList<Users> listUser =new ArrayList<>();
       try{
      if (cn==null){
          JOptionPane.showMessageDialog(this, "Pas de connexion");}
          else
          {  
            int row = tab_Utilisateur.getSelectedRow();
            String value = (tab_Utilisateur.getModel().getValueAt(row, 0).toString());
            ps=cn.prepareStatement("delete from utilisateur where idUtilisateur="+value );
            ps.executeUpdate();
            
          }}catch(Exception e)
          {
          {JOptionPane.showMessageDialog(this, e); }
          }
    }//GEN-LAST:event_SuppBtnActionPerformed

    private void NewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewBtnActionPerformed
        IDTxt.setText(" ");
        NomTxt.setText(" ");
        PrenomTxt.setText(" ");
        MailTxt.setText(" ");
        TelTxt.setText(" ");
        PasswordTxt.setText("  ");

    }//GEN-LAST:event_NewBtnActionPerformed

    private void AfficherBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AfficherBtnActionPerformed
      Connection cn;
      PreparedStatement ps;
      ResultSet rs;
      ArrayList<Users> listUser =new ArrayList<>();
      cn=connecter();
      try{
      if (cn==null){
          JOptionPane.showMessageDialog(this, "Pas de connexion");}
          else
          {
            ps=cn.prepareStatement("select * from utilisateur ");
            rs=ps.executeQuery();
            Users util;
            while(rs.next())
            {
               util= new Users(rs.getInt("idUtilisateur"),rs.getString("nomUtilisateur"),rs.getString("prenomUtilisateur"),rs.getString("mailUtilisateur"),rs.getInt("telUtilisateur"),rs.getString("password"));
               listUser.add(util);
            }
         }
      }catch(Exception e)
      {JOptionPane.showMessageDialog(this, "il existe une erreur"); }
        DefaultTableModel model=(DefaultTableModel) tab_Utilisateur.getModel();
        Object[] row = new Object[6];
      for(int i=0;i<listUser.size();i++)
      {
          row[0]=listUser.get(i).getIdUtilisateur();
          row[1]=listUser.get(i).getNomUtilisateur();
          row[2]=listUser.get(i).getPrenomUtlisateur(); 
          row[3]=listUser.get(i).getMailUtlisateur();
          row[4]=listUser.get(i).getTelUtlisateur();
          row[5]=listUser.get(i).getPassword();
          model.addRow(row);
      }
    }//GEN-LAST:event_AfficherBtnActionPerformed

    
    private void tab_UtilisateurMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab_UtilisateurMouseClicked
        int row = tab_Utilisateur.getSelectedRow();
        TableModel model = tab_Utilisateur.getModel();
        IDTxt.setText(model.getValueAt(row,0).toString());
        NomTxt.setText(model.getValueAt(row,1).toString());
        PrenomTxt.setText(model.getValueAt(row,2).toString());
        MailTxt.setText(model.getValueAt(row,3).toString());
        TelTxt.setText(model.getValueAt(row,4).toString());
        PasswordTxt.setText(model.getValueAt(row,5).toString());
    }//GEN-LAST:event_tab_UtilisateurMouseClicked

    private void RefreshMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RefreshMouseClicked
         DefaultTableModel model =(DefaultTableModel) tab_Utilisateur.getModel();
         model.setRowCount(0);
    }//GEN-LAST:event_RefreshMouseClicked
 
    public Connection connecter(){
     String url ="jdbc:mysql://localhost:3306/gestionmagasin?zeroDateTimeBehavior=convertToNull";
     Connection cn;
     String user="root";
     String password="";
        try{
            cn=DriverManager.getConnection(url,user,password);
            return cn;
            
        }catch(Exception Ex){ return null;}
        
 }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Utilisateurs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Utilisateurs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Utilisateurs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Utilisateurs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Utilisateurs().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AfficherBtn;
    private javax.swing.JTextField IDTxt;
    private javax.swing.JTextField MailTxt;
    private javax.swing.JButton NewBtn;
    private javax.swing.JTextField NomTxt;
    private javax.swing.JPasswordField PasswordTxt;
    private javax.swing.JTextField PrenomTxt;
    private javax.swing.JLabel Refresh;
    private javax.swing.JButton SuppBtn;
    private javax.swing.JTextField TelTxt;
    private javax.swing.JButton UpdateBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tab_Utilisateur;
    // End of variables declaration//GEN-END:variables
}
