/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetfst;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Hp
 */
public class Ventes extends javax.swing.JFrame {

    
    
    public Ventes() {
        initComponents();
        RemplirComboIDClient();
        RemplirComboIDPrd();
        RemplirComboIDFactureC();
        RemplirComboEtat();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tab_Vente = new javax.swing.JTable();
        serchVente = new javax.swing.JTextField();
        Refrech = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        CmbIDFactureC = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        CmbEtat = new javax.swing.JComboBox();
        CmbTypeClient = new javax.swing.JComboBox();
        prixVente = new javax.swing.JTextField();
        RemisePrdVente = new javax.swing.JTextField();
        DesiVente = new javax.swing.JTextField();
        CmbIDPrd = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        IDVenteTxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        qteTxt = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        CmbnomClient = new javax.swing.JComboBox();
        jLabel13 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("Ventes"); // NOI18N

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ID produit");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 174, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Designation");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 221, -1, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("ID livraison");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 128, -1, -1));

        jLabel7.setFont(new java.awt.Font("French Script MT", 1, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageProjet/icons8-sales-performance-50.png"))); // NOI18N
        jLabel7.setText("Livraison");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, 230, -1));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.white, java.awt.Color.white));
        jPanel4.setOpaque(false);
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tab_Vente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Livraison", "Quantité", "Designation", "Date livraison", "Remise", "Prix", "ID Client", "ID Produit", "Somme"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tab_Vente);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 540, 966, 148));
        jPanel4.add(serchVente, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 490, 469, 33));

        Refrech.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageProjet/icons8-refresh-35.png"))); // NOI18N
        Refrech.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RefrechMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                RefrechMousePressed(evt);
            }
        });
        jPanel4.add(Refrech, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 490, 52, -1));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jButton1.setText("Affecter");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 490, 190, 33));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jButton2.setText("Chercher");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 490, 190, 33));

        CmbIDFactureC.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        CmbIDFactureC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CmbIDFactureCActionPerformed(evt);
            }
        });
        jPanel4.add(CmbIDFactureC, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 380, 416, 28));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Etat de livraison");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, -1, -1));

        CmbEtat.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jPanel4.add(CmbEtat, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 420, 416, 28));

        CmbTypeClient.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        CmbTypeClient.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CmbTypeClientItemStateChanged(evt);
            }
        });
        CmbTypeClient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CmbTypeClientMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CmbTypeClientMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CmbTypeClientMousePressed(evt);
            }
        });
        CmbTypeClient.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                CmbTypeClientKeyPressed(evt);
            }
        });
        jPanel4.add(CmbTypeClient, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 300, 416, 28));
        jPanel4.add(prixVente, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, 416, 31));

        RemisePrdVente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemisePrdVenteActionPerformed(evt);
            }
        });
        jPanel4.add(RemisePrdVente, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, 416, 32));
        jPanel4.add(DesiVente, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 416, 31));

        CmbIDPrd.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        CmbIDPrd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CmbIDPrdMouseClicked(evt);
            }
        });
        jPanel4.add(CmbIDPrd, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 416, 28));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("ID facture");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, -1, -1));

        IDVenteTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDVenteTxtActionPerformed(evt);
            }
        });
        jPanel4.add(IDVenteTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, 416, 30));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Prix");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Remise");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nom client");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, -1, -1));

        qteTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qteTxtActionPerformed(evt);
            }
        });
        jPanel4.add(qteTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, 416, 30));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Quantité");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, -1, -1));

        CmbnomClient.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jPanel4.add(CmbnomClient, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 340, 416, 28));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("ID client");
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, -1, -1));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 1040, 720));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageProjet/bg-5-full.jpg"))); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, 790));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IDVenteTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDVenteTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDVenteTxtActionPerformed

    private void CmbIDPrdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CmbIDPrdMouseClicked
        Connection cn;
        PreparedStatement ps;
        cn=connecter();
        try{
            if (cn==null){
                JOptionPane.showMessageDialog(this, "Pas de connexion");
            }
            else {
                ps=cn.prepareStatement("select designation,remise,prix from produit where idProduit="+CmbIDPrd.getSelectedItem());
                ResultSet rs=ps.executeQuery();
                while(rs.next())
                {
                    DesiVente.setText(rs.getString("designation"));
                    RemisePrdVente.setText(rs.getString("remise"));
                    prixVente.setText(rs.getString("prix"));
                }
            }
        }catch(Exception Ex){}

    }//GEN-LAST:event_CmbIDPrdMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Connection cn;
        PreparedStatement ps;
        ResultSet rs;
        ArrayList<Vente> listVente =new ArrayList<>();
        cn=connecter();

        try{
            if (cn==null){
                JOptionPane.showMessageDialog(this, "Pas de connexion");}
            else
            {
                ps=cn.prepareStatement("select idVente,qte,designationV,dateFactureC,remisePrd,prixVente,c.idClient,p.idProduit from client c,vente v,Produit p,factureClient F where v.idClient=c.idClient and p.idProduit=v.idProduit and v.idFactureClient=F.idFactureClient and v.idClient= "+serchVente.getText());
                rs=ps.executeQuery();
                while(rs.next())
                {
                    int prix=(int) rs.getDouble("prixVente");
                    int qte=rs.getInt("qte");
                    int remise=rs.getInt("remisePrd");
                    double cout = prix*qte;
                    double somme=(cout-(cout*remise/100)) ;
                    Vente v = new Vente(rs.getInt("idVente"),qte,prix,remise,rs.getInt("idClient"),rs.getInt("idProduit"),rs.getString("designationV"),somme,rs.getString("dateFactureC"));
                    listVente.add(v);
                }
            }
        }catch(Exception e)
        {JOptionPane.showMessageDialog(this,e); }
        
        DefaultTableModel model=(DefaultTableModel) tab_Vente.getModel();
        Object[] row = new Object[9];
        for(int i=0;i<listVente.size();i++)
        {
            row[0]=listVente.get(i).getIdVente();
            row[1]=listVente.get(i).getQte();
            row[2]=listVente.get(i).getDesignation();
            row[3]=listVente.get(i).getDateL();
            row[4]=listVente.get(i).getRemise();
            row[5]=listVente.get(i).getPrixVente();
            row[6]=listVente.get(i).getIdClient();
            row[7]=listVente.get(i).getIdProduit();
            row[8]=listVente.get(i).getSomme();
            model.addRow(row);
        }
       
    }//GEN-LAST:event_jButton2ActionPerformed
       
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Connection cn;
        PreparedStatement ps;
        cn=connecter();
        try{
            if (cn==null){
                JOptionPane.showMessageDialog(this, "Pas de connexion");
            }
            else {
                if(IDVenteTxt.getText().equals("") || DesiVente.getText().equals("") ||RemisePrdVente.getText().equals("")|| qteTxt.getText().equals("") || prixVente.getText().equals("")  )
                {JOptionPane.showMessageDialog(this, "SVP entrer vos donneé"); }
                else{
                    if(!test_stock()){
                    JOptionPane.showMessageDialog(this, "La quantité demandée est hors stock ");                    
                    }
                    else
                    {
                    ps = cn.prepareStatement("insert into vente(idVente,qte,prixVente,remisePrd,idClient,nomClient,idProduit,designationV,idFactureClient,idEtat) values(?,?,?,?,?,?,?,?,?,?)");
                    ps.setString(1,IDVenteTxt.getText());
                    ps.setString(2,qteTxt.getText());
                    ps.setString(3,prixVente.getText());
                    ps.setString(4,RemisePrdVente.getText());
                    ps.setInt(5,CmbTypeClient.getSelectedIndex()+1);
                    ps.setString(7,CmbIDPrd.getSelectedItem().toString());
                    ps.setString(8,DesiVente.getText());
                    ps.setString(9,CmbIDFactureC.getSelectedItem().toString());
                    ps.setInt(10,CmbEtat.getSelectedIndex()+1);
                    ps.setString(6,CmbnomClient.getSelectedItem().toString());
                    ps.executeUpdate();
                    JOptionPane.showMessageDialog(this, "L'Ajout est fait avec succés");
                    ActualiserStock();
                    ModifierStock();
                    }
                }}
            }catch(Exception e){
                JOptionPane.showMessageDialog(this, e);
                System.out.print(e);
            }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void RefrechMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RefrechMouseClicked
         DefaultTableModel model =(DefaultTableModel) tab_Vente.getModel();
         model.setRowCount(0);    }//GEN-LAST:event_RefrechMouseClicked

    private void RemisePrdVenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemisePrdVenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RemisePrdVenteActionPerformed

    private void CmbIDFactureCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CmbIDFactureCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CmbIDFactureCActionPerformed

    private void RefrechMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RefrechMousePressed
      
     IDVenteTxt.setText(" ");
     qteTxt.setText(" ");
     prixVente.setText(" ");
     RemisePrdVente.setText(" ");
     CmbTypeClient.setSelectedIndex(0);
     CmbIDPrd.setSelectedIndex(0);
     DesiVente.setText(" ");
     CmbIDFactureC.setSelectedIndex(0);
     CmbEtat.setSelectedIndex(0);
     
    }//GEN-LAST:event_RefrechMousePressed

    private void qteTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qteTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qteTxtActionPerformed

    private void CmbTypeClientMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CmbTypeClientMousePressed
 
    }//GEN-LAST:event_CmbTypeClientMousePressed

    private void CmbTypeClientKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CmbTypeClientKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_CmbTypeClientKeyPressed

    private void CmbTypeClientMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CmbTypeClientMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_CmbTypeClientMouseEntered

    private void CmbTypeClientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CmbTypeClientMouseClicked
       
    }//GEN-LAST:event_CmbTypeClientMouseClicked

    private void CmbTypeClientItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CmbTypeClientItemStateChanged
        
        String value=(String) CmbTypeClient.getSelectedItem().toString();
        DefaultComboBoxModel dm = new DefaultComboBoxModel();
        CmbnomClient.setModel(dm);
        if(value.equals("Administration"))
        {
            RemplirComboAdmin(); 
        }
        CmbnomClient.setModel(dm);
        if(value.equals("Formation continue"))
        {
            RemplirComboFormation();
        }
        CmbnomClient.setModel(dm);
        if(value.equals("Laboratoires"))
        {
            RemplirComboLabo(); 
        }
        CmbnomClient.setModel(dm);
        if(value.equals("Départements"))
        {
            RemplirComboDept(); 
        }
        CmbnomClient.setModel(dm);
    }//GEN-LAST:event_CmbTypeClientItemStateChanged

    public Connection connecter(){
     
     String url ="jdbc:mysql://localhost:3306/gestionmagasin?zeroDateTimeBehavior=convertToNull";
     Connection cn;
     String user="root";
     String password="";
        try{
            cn=DriverManager.getConnection(url,user,password);
            return cn;
            
        }catch(Exception Ex){ return null;}
        
 }
     public void RemplirComboEtat(){
        Connection cn;
        PreparedStatement ps;
        cn=connecter();
        try{
            if (cn==null){
                JOptionPane.showMessageDialog(this, "Pas de connexion");
            }
            else {
                ps=cn.prepareStatement("select libelleEtat from EtatVente");
                ResultSet rs=ps.executeQuery();
                while(rs.next())
                {
                CmbEtat.addItem(rs.getString("libelleEtat"));
                 }
        }
            
            }catch(Exception Ex){}
    }
    public void RemplirComboIDPrd(){
        Connection cn;
        PreparedStatement ps;
        cn=connecter();
        try{
            if (cn==null){
                JOptionPane.showMessageDialog(this, "Pas de connexion");
            }
            else {
                ps=cn.prepareStatement("select * from produit ");
                ResultSet rs=ps.executeQuery();
                while(rs.next())
                {
                CmbIDPrd.addItem(rs.getString("idProduit"));
                 }
        }
            }catch(Exception Ex){}
    }
    public void RemplirComboIDClient(){
        Connection cn;
        PreparedStatement ps;
        cn=connecter();
        try{
            if (cn==null){
                JOptionPane.showMessageDialog(this, "Pas de connexion");
            }
            else {
                ps=cn.prepareStatement("select * from client");
                ResultSet rs=ps.executeQuery();
                while(rs.next())
                {
                CmbTypeClient.addItem(rs.getString("nomClient"));
                 }
        }
            
            }catch(Exception Ex){}
    }
    int now ;
    public void ActualiserStock() {
       Connection cn;
        PreparedStatement ps;
        cn=connecter();
         int   qtePrdAct = 0,qteStock = 0;
        try{
            if (cn==null){
                JOptionPane.showMessageDialog(this, "Pas de connexion");
            }
            else {
     
                ps=cn.prepareStatement("select nbrProduit ,qte from Stock s ,produit p ,vente v where s.idStock=p.idStock and v.idProduit=p.idProduit and v.idProduit="+CmbIDPrd.getSelectedItem());
                ResultSet rs=ps.executeQuery();
                while(rs.next())
                {
                  qtePrdAct =rs.getInt("qte");
                  qteStock=rs.getInt("nbrProduit");
                 }  
                  now =qteStock - qtePrdAct ;
                  ps =cn.prepareStatement("UPDATE produit,stock SET nbrProduit="+now +" where produit.idStock=stock.idstock and idProduit="+CmbIDPrd.getSelectedItem());
                  ps.executeUpdate();
        }
            }catch(Exception Ex){ } 
    }
    public void RemplirComboIDFactureC(){
        Connection cn;
        PreparedStatement ps;
        cn=connecter();
        try{
            if (cn==null){
                JOptionPane.showMessageDialog(this, "Pas de connexion");
            }
            else {
                ps=cn.prepareStatement("select * from FactureClient");
                ResultSet rs=ps.executeQuery();
                while(rs.next())
                {
                CmbIDFactureC.addItem(rs.getInt("idFactureClient"));
                 }
        }
            }catch(Exception Ex){}
    }
   
    public void RemplirComboDept(){
        Connection cn;
        PreparedStatement ps;
        cn=connecter();
        try{
            if (cn==null){
                JOptionPane.showMessageDialog(this, "Pas de connexion");
            }
            else {
                ps=cn.prepareStatement("select * from departements");
                ResultSet rs=ps.executeQuery();
                while(rs.next())
                {
                CmbnomClient.addItem(rs.getString("nomDept"));
                 }
        }
            }catch(Exception Ex){}
    }
    
    public void RemplirComboLabo(){
        Connection cn;
        PreparedStatement ps;
        cn=connecter();
        try{
            if (cn==null){
                JOptionPane.showMessageDialog(this, "Pas de connexion");
            }
            else {
                ps=cn.prepareStatement("select * from laboratoires");
                ResultSet rs=ps.executeQuery();
                while(rs.next())
                {
                CmbnomClient.addItem(rs.getString("nomLabo"));
                 }
        }
            }catch(Exception Ex){}
    }
    
    public void RemplirComboFormation(){
        Connection cn;
        PreparedStatement ps;
        cn=connecter();
        try{
            if (cn==null){
                JOptionPane.showMessageDialog(this, "Pas de connexion");
            }
            else {
                ps=cn.prepareStatement("SELECT * FROM `formation continue`");
                ResultSet rs=ps.executeQuery();
                while(rs.next())
                {
                CmbnomClient.addItem(rs.getString("libelleFormation"));
                 }
        }
            }catch(Exception Ex){}
    }
    public void RemplirComboAdmin(){
        Connection cn;
        PreparedStatement ps;
        cn=connecter();
        try{
            if (cn==null){
                JOptionPane.showMessageDialog(this, "Pas de connexion");
            }
            else {
                
                ps=cn.prepareStatement("SELECT * FROM administration");
                ResultSet rs=ps.executeQuery();
                while(rs.next())
                {
                CmbnomClient.addItem(rs.getString("libelleAdmin"));
                 }
        }
            }catch(Exception Ex){}
    }
    
    public boolean test_stock() throws SQLException {
        Connection cn = connecter() ;
        PreparedStatement ps;
        boolean teststock ;
       
                ps=cn.prepareStatement("SELECT qteProduitStock FROM Produit p,stock s where p.idStock=s.idStock and idProduit="+CmbIDPrd.getSelectedItem());
                ResultSet rs=ps.executeQuery();
                int old = 0 ;
                while (rs.next()) {
                      old = rs.getInt("qteProduitStock");
                 }
             int  dec = Integer.parseInt(qteTxt.getText());
             if (old < dec)
             {
              teststock = false;
             } 
             else 
             {
            teststock = true;
             }
             return teststock ;
                 
    }
    
     public void ModifierStock(){
        Connection cn;
        PreparedStatement ps;
        cn=connecter();
        int qteStock = 0;
        try{
            if (cn==null){
                JOptionPane.showMessageDialog(this, "Pas de connexion");
            }
            else {
                 ps=cn.prepareStatement("select qteProduitStock from Stock s ,produit p  where s.idStock=p.idStock and p.idProduit="+CmbIDPrd.getSelectedItem());
                ResultSet rs=ps.executeQuery();
                while(rs.next())
                {
                 qteStock=rs.getInt("qteProduitStock");
                 }  
                 int now=qteStock-Integer.parseInt(qteTxt.getText());
                  ps =cn.prepareStatement("UPDATE produit,stock SET qteProduitStock="+now +" where produit.idStock=stock.idstock and idProduit="+CmbIDPrd.getSelectedItem());
                  ps.executeUpdate();
        }
            }catch(Exception Ex){}  
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox CmbEtat;
    private javax.swing.JComboBox CmbIDFactureC;
    private javax.swing.JComboBox CmbIDPrd;
    private javax.swing.JComboBox CmbTypeClient;
    private javax.swing.JComboBox CmbnomClient;
    private javax.swing.JTextField DesiVente;
    private javax.swing.JTextField IDVenteTxt;
    private javax.swing.JLabel Refrech;
    private javax.swing.JTextField RemisePrdVente;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField prixVente;
    private javax.swing.JTextField qteTxt;
    private javax.swing.JTextField serchVente;
    private javax.swing.JTable tab_Vente;
    // End of variables declaration//GEN-END:variables
}
